import json
import logging
import re
from celery import Celery
from celery.schedules import crontab

from app.agent import handle_incident
from app.config import get_settings

settings = get_settings()

celery_app = Celery("k8s_agent", broker=settings.celery_broker_url, backend=settings.celery_result_backend)
celery_app.conf.update(task_track_started=True)

# Schedule the polling task every 60 seconds
celery_app.conf.beat_schedule = {
    "poll-jira-every-60-seconds": {
        "task": "app.worker.poll_jira_for_remediation",
        "schedule": 60.0,
    },
}

logger = logging.getLogger(__name__)


@celery_app.task(name="app.worker.process_incident")
def process_incident(payload: dict) -> dict:
    from redis import Redis
    s = get_settings()
    redis_client = Redis.from_url(s.redis_url, decode_responses=True)
    return handle_incident(payload, s, redis_client)


@celery_app.task(name="app.worker.poll_jira_for_remediation")
def poll_jira_for_remediation() -> dict:
    from app.clients.github import GitHubClient
    from app.clients.jira import JiraClient
    from app.clients.llm import LLMClient
    from app.schemas import JiraIssue

    s = get_settings()
    jira = JiraClient(s)
    github = GitHubClient(s)
    llm = LLMClient(s)

    logger.info("Polling Jira for issues requiring remediation...")
    
    jql = f'project = "{s.jira_project_key}" AND status = "To Do" AND labels = "AI-Remediation"'
    issues = jira.search_issues(jql)
    
    processed_count = 0
    for issue_data in issues:
        issue_key = issue_data["key"]
        issue = JiraIssue(key=issue_key, url=f"{s.jira_base_url}/browse/{issue_key}")
        
        logger.info("Picking up issue %s for iterative remediation", issue_key)
        jira.transition_issue(issue, "In Progress")
        
        # 1. Gather context from Jira
        details = jira.get_issue_details(issue_key)
        description = details["description"]
        human_comments = details["comments"]
        
        # Extract workload name from JSON block in description
        workload_name = None
        match = re.search(r"\{code:json\}(.*?)\{code\}", description, re.DOTALL)
        if match:
            try:
                context_data = json.loads(match.group(1).strip())
                workload_name = context_data.get("workload_name")
            except Exception as e:
                logger.error("Failed to parse JSON context from %s: %s", issue_key, e)
                
        if not workload_name:
            jira.add_comment(issue, "❌ Auto-remediation failed: could not extract workload_name from issue description.")
            jira.transition_issue(issue, "To Do")
            continue
            
        # 2. Gather context from GitHub (existing PR comments)
        branch = f"ai-fix/{issue_key.lower()}"
        pr_comments = github.get_pr_comments(branch)
        all_comments = human_comments + pr_comments
        
        # 3. Fetch original YAML
        file_path = f"deploy/workloads/{workload_name}.yaml"
        original_yaml, _ = github.get_file_content(file_path, ref="main")
        if not original_yaml:
            jira.add_comment(issue, f"❌ Auto-remediation failed: file {file_path} not found in repo.")
            jira.transition_issue(issue, "To Do")
            continue

        # 4. LLM Rewrite
        new_yaml = llm.rewrite_yaml(original_yaml, all_comments)
        
        # 5. Push and PR
        commit_msg = f"[{issue_key}] Auto-remediation update for {workload_name}"
        github.push_file(branch, file_path, new_yaml, commit_msg)
        
        pr_title = f"[{issue_key}] Remediation for {workload_name}"
        pr_body = f"Iterative remediation generated by K8s-Agent based on human feedback."
        pr = github.create_or_update_pr(pr_title, pr_body, branch)
        
        # 6. Finalize Jira
        jira.add_comment(issue, f"## 🤖 Agent Iteration Complete\n\nI have updated the code based on the feedback. Please review the PR: [{pr.title}]({pr.url})")
        jira.transition_issue(issue, "In Review")
        
        processed_count += 1
        
    return {"status": "success", "processed": processed_count}
